version: 2.1
orbs:
  architect: giantswarm/architect@4.35.6

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: "app-build-suite"
          name: "package and push datadog chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "datadog"
          ct_config: ".circleci/ct-config.yaml"
          push_to_oci_registry: true
          filters:
            tags:
              only: /^v.*/
