{{- if .Values.kyvernoPolicyExceptions.enabled }}
{{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{ include "datadog.labels" . | nindent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-exceptions
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ template "datadog.fullname" . }}-cluster-agent*
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{ include "datadog.labels" . | nindent 4 }}
  name: {{ template "datadog.fullname" . }}-exceptions
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ template "datadog.fullname" . }}*
{{- end -}}
{{- end -}}
