checks:
  addAllBuiltIn: true
  exclude:
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
  - "no-read-only-root-fs"
  - "run-as-non-root"
  - "required-annotation-email"
  - "required-label-owner"
  - "no-liveness-probe"
  - "no-readiness-probe"
  - "sensitive-host-mounts"
  - "writable-host-mount"
  # Chart dependency 'datadog-crds' defines a CRD using apiextensions.k8s.io/v1beta1
  - "no-extensions-v1beta"
