apiVersion: v1
name: datadog
version: 2.30.19
appVersion: "7"
description: Datadog Agent
keywords:
- monitoring
- alerting
- metric
home: https://www.datadoghq.com
icon: https://s.giantswarm.io/app-icons/datadog/1/light.svg
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
maintainers:
- name: Datadog
  email: support@datadoghq.com
