datadog:
  datadog:
    kubelet:
      hostCAPath: /var/lib/kubelet/pki/kubelet.crt

  clusterAgent:
    podSecurity:
      podSecurityPolicy:
        create: true

  agents:
    podSecurity:
      podSecurityPolicy:
        create: true
      securityContext:
        seLinuxOptions: {}
      seLinuxContext:
        seLinuxOptions: {}

      apparmor:
        enabled: false
