# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

datadog:
  datadog:
    kubelet:
      hostCAPath: /var/lib/kubelet/pki/kubelet.crt

  clusterAgent:
    podSecurity:
      podSecurityPolicy:
        create: true
    
    replicas: 2

    createPodDisruptionBudget: true

  agents:
    podSecurity:
      apparmor:
        enabled: false
      podSecurityPolicy:
        create: true
      securityContext:
        seLinuxOptions: {}
      seLinuxContext:
        seLinuxOptions: {}
      seccompProfiles:
      - "runtime/default"
    
    containers:
      agent: 
        securityContext:
          seccompProfile:
            type: RuntimeDefault
