datadog:
  datadog:
    kubelet:
      hostCAPath: /var/lib/kubelet/pki/kubelet.crt

  clusterAgent:
    podSecurity:
      podSecurityPolicy:
        create: true
    
    replicas: 2

    createPodDisruptionBudget: true

  agents:
    podSecurity:
      podSecurityPolicy:
        create: true
      securityContext:
        seLinuxOptions: {}
      seLinuxContext:
        seLinuxOptions: {}
      seccompProfiles:
      - "runtime/default"

      apparmor:
        enabled: false
    
    containers:
      agent: 
        securityContext:
          seccompProfile:
            type: RuntimeDefault
