datadog:
  datadog:
    kubelet:
      hostCAPath: /var/lib/kubelet/pki/kubelet.crt

  clusterAgent:
    image:
      tag: 7.40.0

    podSecurity:
      podSecurityPolicy:
        create: true

  agents:
    image:
      tag: 7.40.0

    podSecurity:
      podSecurityPolicy:
        create: true
      securityContext:
        seLinuxOptions: {}
      seLinuxContext:
        seLinuxOptions: {}

      apparmor:
        enabled: false
  clusterChecksRunner:
    image:
      tag: 7.40.0
